using System;
using System.Collections.Generic;
using UnityEngine;

namespace Mr1
{
    public class MouseClickDemo : MonoBehaviour
    {
        public Transform target;
        public string pathName;

        public GameObject playerObj;


        void Update () 
        {
            if ( Input.GetMouseButtonUp(0))
            {
                OnMouseUp();
            }

        }
        void OnMouseUp()
        {
			WaypointManager.instance.SelectPath ( 0 );
            //WaypointManager.instance.selected.Refresh();
            {
                float startTime = Time.realtimeSinceStartup;
                Debug.Log("Hello: Start Time : " + Time.realtimeSinceStartup );
                WaypointManager.instance.FindShortestPathAsynchronous( 1, 8, delegate ( List<WayPoint> wayPoints ) 
                { 
                    string str = "";
                    if ( wayPoints != null )
                    {
                        foreach ( var a in wayPoints ) 
                        {
                            str += "=>" + a.autoGeneratedID.ToString();
                        }
                    }
                    Debug.LogWarning("Path: " + str);
                    Debug.Log("Time Taken:" + (Time.realtimeSinceStartup - startTime));

                    //List<Vector3> path = SetStraightLine ( wayPoints );
                    List<Vector3> path = WaypointManager.GetCatmullRomCurvePathPoints ( wayPoints );
                    //PathFinderUtility.FollowPath( playerObj.transform, path, 100.0f );
                    PathFinderUtility.FollowPathWithGroundSnap ( playerObj.transform, path, 20.0f, Vector3.down, 5, 0.1f, 200, LayerMask.NameToLayer("Default"));
                } );
            }

            // var targetPos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            // targetPos.z = transform.position.z;
            // target.FollowPathToPoint(pathName, targetPos, 10f);
        }

        

        
    }
}
