using System;
using System.Collections.Generic;
using UnityEngine;

namespace Mr1
{
    public class MouseClickDemo : MonoBehaviour
    {
        public Transform target;
        public string pathName;


        void Update () 
        {
            if ( Input.GetMouseButtonUp(0))
            {
                OnMouseUp();
            }

        }
        void OnMouseUp()
        {
			WaypointManager.instance.SelectPath ( 0 );
            //WaypointManager.instance.selected.Refresh();
            {
                float startTime = Time.realtimeSinceStartup;
                Debug.Log("Hello: Start Time : " + Time.realtimeSinceStartup );
                WaypointManager.instance.FindShortestPathAsynchronous( 1, 14, delegate ( List<WayPoint> wayPoints ) 
                { 
                    string str = "";
                    if ( wayPoints != null )
                        foreach ( var a in wayPoints ) 
                        {
                            str += "=>" + a.autoGeneratedID.ToString();
                        }
                    Debug.LogWarning("Path: " + str);
                    Debug.Log("Time Taken:" + (Time.realtimeSinceStartup - startTime));
                } );
            }

            // var targetPos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            // targetPos.z = transform.position.z;
            // target.FollowPathToPoint(pathName, targetPos, 10f);
        }
    }
}
