using UnityEngine;
using QPathFinder;
using System;
using System.Collections;
using System.Collections.Generic;

namespace QPathFinder
{
    /*
        PathFinder instance uses GraphData to find the way points and paths. 
        Using them, it will find the path from source node to destination node. 
     */
    public class PathFinder : MonoBehaviour
    {
        private static PathFinder _instance;
        public static PathFinder instance { get { return _instance; } }

        public GraphData graphData = new GraphData();
        
        public void Awake()
        {
            _instance = this;
        }
        public void OnDestroy ()
        {
            _instance = null;
        }

        // Finds shortest path Asynchronously. This method will not lock the control. 
        // Once the path if found, it will return the path as List of nodes. 
        // You can use PathFollower to follow the list of nodes. 
        // The time it takes to find the path depends on how many nodes are there between source and destination. 
        
        public void FindShortestPathAsynchronous ( int fromNodeID, int toNodeId, Action<List<Node>> callback )
        {
            if ( QPathFinder.Logger.CanLogInfo ) QPathFinder.Logger.LogInfo(" FindShortestPathAsynchronous triggered from " + fromNodeID + " to " + toNodeId , true );
            StartCoroutine( FindShortestPathAsynchonousInternal( fromNodeID, toNodeId, callback ) );
        }

        // Finds shortest path immediately. 
        // As long as your grid is smaller ( 10 - 30 nodes ), this shouldnt cause performance drops. 
        
        public List<Node> FindShortestPathSynchronous( int fromNodeID, int toNodeID )
        {
            if ( QPathFinder.Logger.CanLogInfo ) QPathFinder.Logger.LogInfo(" FindShortestPathSynchronous triggered from " + fromNodeID + " to " + toNodeID, true);
            return FindShortedPathSynchronousInternal ( fromNodeID, toNodeID );
        }

        public int FindNearestNode ( Vector3 point )
		{
			float minDistance = float.MaxValue;
			Node nearestWayPoint = null;

			foreach ( var wayPoint in graphData.nodes )
			{
				if ( Vector3.Distance ( wayPoint.Position, point ) < minDistance ) 
				{
					minDistance = Vector3.Distance ( wayPoint.Position, point );
					nearestWayPoint = wayPoint;
				}
			}

			return nearestWayPoint != null ? nearestWayPoint.autoGeneratedID : -1;
		}

        /*** Protected & Private ***/
        #region PRIVATE

        protected IEnumerator FindShortestPathAsynchonousInternal ( int fromNodeID, int toNodeID, Action<List<Node>> callback )
        {
            if ( callback == null )
                yield break;

            int startPointID = fromNodeID; 
            int endPointID = toNodeID;
            bool found = false;

            graphData.ReGenerateIDs();

            Node startPoint = graphData.nodesSorted[startPointID];
            Node endPoint = graphData.nodesSorted[endPointID];

            foreach( var point in graphData.nodes )
            {
                point.heuristicDistance = -1;
                point.previousWayPoint = null;
            }

            List<Node> completedPoints = new List<Node>();
            List<Node> nextPoints = new List<Node>();
            List<Node> finalPath = new List<Node>();

            startPoint.pathDistance = 0;
            startPoint.heuristicDistance = Vector3.Distance ( startPoint.Position, endPoint.Position );
            nextPoints.Add( startPoint );

            while ( true )
            {
                Node leastCostPoint = null; 
                
                float minCost = 99999;
                foreach ( var point in nextPoints )
                {
                    if ( point.heuristicDistance <= 0 )
                        point.heuristicDistance = Vector3.Distance ( point.Position, endPoint.Position );

                    if ( minCost > point.combinedHeuristic )
                    {
                        leastCostPoint = point;
                        minCost = point.combinedHeuristic;
                    }
                }

                if ( leastCostPoint == null ) 
                    break;
                
                if ( leastCostPoint == endPoint )
                {
                    found = true;
                    Node prevPoint = leastCostPoint;
                    while ( prevPoint != null ) 
                    {
                        finalPath.Insert(0, prevPoint);
                        prevPoint = prevPoint.previousWayPoint;
                    }

                    if ( QPathFinder.Logger.CanLogInfo ) 
                    {
                        if ( finalPath != null )
                        {
                            string str = "";
                            foreach ( var a in finalPath ) 
                            {
                                str += "=>" + a.autoGeneratedID.ToString();
                            }
                            QPathFinder.Logger.LogInfo("Path found between " + fromNodeID + " and " + toNodeID + ":" + str , true );
                        }
                    }
                    callback ( finalPath );
                    yield break;
                }
    
                foreach ( var path in graphData.paths )
                {
                    if ( path.IDOfA == leastCostPoint.autoGeneratedID 
                    || path.IDOfB == leastCostPoint.autoGeneratedID )
                    {
                        Node otherPoint = path.IDOfA == leastCostPoint.autoGeneratedID ? 
                                                graphData.nodesSorted[path.IDOfB] : graphData.nodesSorted[path.IDOfA];

                        if ( otherPoint.heuristicDistance <= 0 )
                            otherPoint.heuristicDistance = Vector3.Distance ( otherPoint.Position, endPoint.Position );

                        if ( completedPoints.Contains ( otherPoint) )
                            continue;

                        if ( nextPoints.Contains( otherPoint ))
                        {
                            if ( otherPoint.pathDistance > 
                                ( leastCostPoint.pathDistance + path.cost ) )
                            {
                                otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                                otherPoint.previousWayPoint = leastCostPoint;
                            }
                        }
                        else
                        {
                            otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                            otherPoint.previousWayPoint = leastCostPoint;
                            nextPoints.Add ( otherPoint );
                        }
                    }
                }

                nextPoints.Remove ( leastCostPoint );
                completedPoints.Add ( leastCostPoint );

                yield return null;
            }       

            if ( !found ) 
            {
                if ( QPathFinder.Logger.CanLogWarning ) QPathFinder.Logger.LogWarning("Path not found between " + fromNodeID + " and " + toNodeID, true );
                callback ( null );
                yield break;
            }
            
            if ( QPathFinder.Logger.CanLogError ) QPathFinder.Logger.LogError("Unknown error while finding the path!", true );

            callback ( null );
            yield break;
        }

        private List<Node> FindShortedPathSynchronousInternal( int fromNodeID, int toNodeID )
        {
            int startPointID = fromNodeID; 
            int endPointID = toNodeID;
            bool found = false;

            graphData.ReGenerateIDs();

            Node startPoint = graphData.nodesSorted[startPointID];
            Node endPoint = graphData.nodesSorted[endPointID];

            foreach( var point in graphData.nodes )
            {
                point.heuristicDistance = -1;
                point.previousWayPoint = null;
            }

            List<Node> completedPoints = new List<Node>();
            List<Node> nextPoints = new List<Node>();
            List<Node> finalPath = new List<Node>();

            startPoint.pathDistance = 0;
            startPoint.heuristicDistance = Vector3.Distance ( startPoint.Position, endPoint.Position );
            nextPoints.Add( startPoint );

            while ( true )
            {
                Node leastCostPoint = null; 
                
                float minCost = 99999;
                foreach ( var point in nextPoints )
                {
                    if ( point.heuristicDistance <= 0 )
                        point.heuristicDistance = Vector3.Distance ( point.Position, endPoint.Position );

                    if ( minCost > point.combinedHeuristic )
                    {
                        leastCostPoint = point;
                        minCost = point.combinedHeuristic;
                    }
                }

                if ( leastCostPoint == null ) 
                    break;
                
                if ( leastCostPoint == endPoint )
                {
                    found = true;
                    Node prevPoint = leastCostPoint;
                    while ( prevPoint != null ) 
                    {
                        finalPath.Insert(0, prevPoint);
                        prevPoint = prevPoint.previousWayPoint;
                    }

                    if ( QPathFinder.Logger.CanLogInfo ) 
                    {
                        if ( finalPath != null )
                        {
                            string str = "";
                            foreach ( var a in finalPath ) 
                            {
                                str += "=>" + a.autoGeneratedID.ToString();
                            }
                            QPathFinder.Logger.LogInfo("Path found between " + fromNodeID + " and " + toNodeID + ":" + str , true );
                        }
                    }

                    return finalPath;
                }
    
                foreach ( var path in graphData.paths )
                {
                    if ( path.IDOfA == leastCostPoint.autoGeneratedID 
                    || path.IDOfB == leastCostPoint.autoGeneratedID )
                    {
                        Node otherPoint = path.IDOfA == leastCostPoint.autoGeneratedID ? 
                                                graphData.nodesSorted[path.IDOfB] : graphData.nodesSorted[path.IDOfA];

                        if ( otherPoint.heuristicDistance <= 0 )
                            otherPoint.heuristicDistance = Vector3.Distance ( otherPoint.Position, endPoint.Position );

                        if ( completedPoints.Contains ( otherPoint) )
                            continue;

                        if ( nextPoints.Contains( otherPoint ))
                        {
                            if ( otherPoint.pathDistance > 
                                ( leastCostPoint.pathDistance + path.cost ) )
                            {
                                otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                                otherPoint.previousWayPoint = leastCostPoint;
                            }
                        }
                        else
                        {
                            otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                            otherPoint.previousWayPoint = leastCostPoint;
                            nextPoints.Add ( otherPoint );
                        }
                    }
                }

                nextPoints.Remove ( leastCostPoint );
                completedPoints.Add ( leastCostPoint );
            }       

            if ( !found ) 
            {
                if ( QPathFinder.Logger.CanLogWarning ) QPathFinder.Logger.LogWarning("Path not found between " + fromNodeID + " and " + toNodeID, true );
                return null;
            }
            
            if ( QPathFinder.Logger.CanLogError ) QPathFinder.Logger.LogError("Unknown error while finding the path!", true );
            return null;
        }
        #endregion // PROTECTED
    }
}
