#define ONE_WAY_LOGIC

using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace Mr1
{
    public enum PathLineType
    {
        Straight,
        CatmullRomCurve,
        BezierCurve,
    }

    [System.Serializable]
    public class WayPoint 
    {
        public WayPoint ( Vector3 pos ) { position = pos; }
        [SerializeField] public Vector3 position;
        [HideInInspector] public int autoGeneratedIndex;
        [HideInInspector] public WayPoint previousWayPoint;
        [HideInInspector] public float  HeuristicDistance;
    }

    [System.Serializable]
    public class WayPath 
    {
        public WayPoint a;
        public WayPoint b;
        public int cost;
#if ONE_WAY_LOGIC
        public bool isOneWay = false;       
#endif
    }


    public class PathData : ScriptableObject
    {
        public bool bShowPath;

        [SerializeField] public string pathName;
        [SerializeField] public PathLineType lineType;
        [SerializeField] public Color lineColor = Color.yellow;
        [SerializeField] public float pointSize = 0.5f;

        [SerializeField] public List<WayPoint> points;
        [SerializeField] public List<WayPath> paths;

        public PathData()
        {
            points = new List<WayPoint>();
            paths = new List<WayPath>();
        }
    }
}