using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using Mr1;

namespace Mr1
{
    public class WaypointManager : MonoBehaviour
    {
        static WaypointManager _instance;
        public static WaypointManager instance { get { return _instance; } }

        public PathData pathData = new PathData();
        
        public void Awake()
        {
            _instance = this;
        }
        public void OnDestroy ()
        {
            _instance = null;
        }


        public void FindShortestPathAsynchronous ( int fromNodeID, int toNodeId, System.Action<List<WayPoint>> callback )
        {
            StartCoroutine( FindShortestPathAsynchonousInternal( fromNodeID, toNodeId, callback ) );
        }

        public List<WayPoint> FindShortedPath( int fromNodeID, int toNodeID )
        {
            int startPointID = fromNodeID; 
            int endPointID = toNodeID;
            bool found = false;

            pathData.Refresh();

            WayPoint startPoint = pathData.pointsSorted[startPointID];
            WayPoint endPoint = pathData.pointsSorted[endPointID];

            foreach( var point in pathData.points )
            {
                point.HeuristicDistance = -1;
                point.previousWayPoint = null;
            }

            List<WayPoint> completedPoints = new List<WayPoint>();
            List<WayPoint> nextPoints = new List<WayPoint>();
            List<WayPoint> finalPath = new List<WayPoint>();

            startPoint.pathDistance = 0;
            startPoint.HeuristicDistance = Vector3.Distance ( startPoint.position, endPoint.position );
            nextPoints.Add( startPoint );

            while ( true )
            {
                WayPoint leastCostPoint = null; 
                
                float minCost = 99999;
                foreach ( var point in nextPoints )
                {
                    if ( point.HeuristicDistance <= 0 )
                        point.HeuristicDistance = Vector3.Distance ( point.position, endPoint.position );

                    if ( minCost > point.combinedHeuristic )
                    {
                        leastCostPoint = point;
                        minCost = point.combinedHeuristic;
                    }
                }

                if ( leastCostPoint == null ) 
                    break;
                
                if ( leastCostPoint == endPoint )
                {
                    found = true;
                    WayPoint prevPoint = leastCostPoint;
                    while ( prevPoint != null ) 
                    {
                        finalPath.Insert(0, prevPoint);
                        prevPoint = prevPoint.previousWayPoint;
                    }

                    return finalPath;
                }
    
                foreach ( var path in pathData.paths )
                {
                    if ( path.IDOfA == leastCostPoint.autoGeneratedID 
                    || path.IDOfB == leastCostPoint.autoGeneratedID )
                    {
                        WayPoint otherPoint = path.IDOfA == leastCostPoint.autoGeneratedID ? 
                                                pathData.pointsSorted[path.IDOfB] : pathData.pointsSorted[path.IDOfA];

                        if ( otherPoint.HeuristicDistance <= 0 )
                            otherPoint.HeuristicDistance = Vector3.Distance ( otherPoint.position, endPoint.position );

                        if ( completedPoints.Contains ( otherPoint) )
                            continue;

                        if ( nextPoints.Contains( otherPoint ))
                        {
                            if ( otherPoint.pathDistance > 
                                ( leastCostPoint.pathDistance + path.cost ) )
                            {
                                otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                                otherPoint.previousWayPoint = leastCostPoint;
                            }
                        }
                        else
                        {
                            otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                            otherPoint.previousWayPoint = leastCostPoint;
                            nextPoints.Add ( otherPoint );
                        }
                    }
                }

                nextPoints.Remove ( leastCostPoint );
                completedPoints.Add ( leastCostPoint );
            }       

            if ( !found ) 
            {
                return null;
            }
            Debug.LogError("Shouldnt be here");
            return null;
        }


        IEnumerator FindShortestPathAsynchonousInternal ( int fromNodeID, int toNodeID, System.Action<List<WayPoint>> callback )
        {
            if ( callback == null )
                yield break;

            int startPointID = fromNodeID; 
            int endPointID = toNodeID;
            bool found = false;

            pathData.Refresh();

            WayPoint startPoint = pathData.pointsSorted[startPointID];
            WayPoint endPoint = pathData.pointsSorted[endPointID];

            foreach( var point in pathData.points )
            {
                point.HeuristicDistance = -1;
                point.previousWayPoint = null;
            }

            List<WayPoint> completedPoints = new List<WayPoint>();
            List<WayPoint> nextPoints = new List<WayPoint>();
            List<WayPoint> finalPath = new List<WayPoint>();

            startPoint.pathDistance = 0;
            startPoint.HeuristicDistance = Vector3.Distance ( startPoint.position, endPoint.position );
            nextPoints.Add( startPoint );

            while ( true )
            {
                WayPoint leastCostPoint = null; 
                
                float minCost = 99999;
                foreach ( var point in nextPoints )
                {
                    if ( point.HeuristicDistance <= 0 )
                        point.HeuristicDistance = Vector3.Distance ( point.position, endPoint.position );

                    if ( minCost > point.combinedHeuristic )
                    {
                        leastCostPoint = point;
                        minCost = point.combinedHeuristic;
                    }
                }

                if ( leastCostPoint == null ) 
                    break;
                
                if ( leastCostPoint == endPoint )
                {
                    found = true;
                    WayPoint prevPoint = leastCostPoint;
                    while ( prevPoint != null ) 
                    {
                        finalPath.Insert(0, prevPoint);
                        prevPoint = prevPoint.previousWayPoint;
                    }

                    callback ( finalPath );
                    yield break;
                }
    
                foreach ( var path in pathData.paths )
                {
                    if ( path.IDOfA == leastCostPoint.autoGeneratedID 
                    || path.IDOfB == leastCostPoint.autoGeneratedID )
                    {
                        WayPoint otherPoint = path.IDOfA == leastCostPoint.autoGeneratedID ? 
                                                pathData.pointsSorted[path.IDOfB] : pathData.pointsSorted[path.IDOfA];

                        if ( otherPoint.HeuristicDistance <= 0 )
                            otherPoint.HeuristicDistance = Vector3.Distance ( otherPoint.position, endPoint.position );

                        if ( completedPoints.Contains ( otherPoint) )
                            continue;

                        if ( nextPoints.Contains( otherPoint ))
                        {
                            if ( otherPoint.pathDistance > 
                                ( leastCostPoint.pathDistance + path.cost ) )
                            {
                                otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                                otherPoint.previousWayPoint = leastCostPoint;
                            }
                        }
                        else
                        {
                            otherPoint.pathDistance = leastCostPoint.pathDistance + path.cost; 
                            otherPoint.previousWayPoint = leastCostPoint;
                            nextPoints.Add ( otherPoint );
                        }
                    }
                }

                nextPoints.Remove ( leastCostPoint );
                completedPoints.Add ( leastCostPoint );

                yield return null;
            }       

            if ( !found ) 
            {
                callback ( null );
                yield break;
            }
            
            Debug.LogError("Shouldnt be here");
            callback ( null );
            yield break;
        }

        


    }
}
